name: Copilot Setup Steps
"on":
  push:
    paths:
    - .github/workflows/copilot-setup-steps.yml
  workflow_dispatch: null
jobs:
  copilot-setup-steps:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Install gh-aw extension
      uses: github/gh-aw-actions/setup-cli@dc50be57c94373431b49d3d0927f318ac2bb5c4c # v0.62.5
      with:
        version: v0.62.5
