name: Release

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to create release for (e.g., v1.0.0)'
        required: true
        type: string

jobs:
  create-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      release_tag: ${{ steps.get_tag.outputs.tag_name }}
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
      
    - name: Get tag name
      id: get_tag
      run: |
        if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
          echo "tag_name=${{ inputs.tag }}" >> $GITHUB_OUTPUT
        else
          echo "tag_name=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
        fi
    
    - name: Create Release
      id: create_release
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh release create "${{ steps.get_tag.outputs.tag_name }}" \
          --title "Release ${{ steps.get_tag.outputs.tag_name }}" \
          --notes "## Release ${{ steps.get_tag.outputs.tag_name }}

        This release was automatically created.

        ### Changes
        See the [commit history](https://github.com/${{ github.repository }}/commits/${{ steps.get_tag.outputs.tag_name }}) for details."

  trigger-maintenance:
    runs-on: ubuntu-latest
    needs: create-release
    if: success()
    permissions:
      actions: write
    
    steps:
    - name: Trigger maintenance workflow
      uses: actions/github-script@v7
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const result = await github.rest.actions.createWorkflowDispatch({
            owner: context.repo.owner,
            repo: context.repo.repo,
            workflow_id: 'maintenance.yml',
            ref: context.payload.repository?.default_branch || 'main',
            inputs: {
              release_tag: '${{ needs.create-release.outputs.release_tag }}'
            }
          });
          console.log('Maintenance workflow triggered successfully');
          console.log('Release tag:', '${{ needs.create-release.outputs.release_tag }}');
